[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32L072KBUx --speed 4600"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[env]
DEFMT_LOG = "debug"

[unstable]
build-std = ["core", "panic_abort"]
build-std-features = ["panic_immediate_abort", "core/turbowakers"]
