[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32L072KBUx --speed 4600"

[build]
target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+

[target.thumbv6m-none-eabi]
rustflags = ["--cfg", "portable_atomic_no_outline_atomics"]

[unstable]
build-std = ["core", "alloc", "panic_abort"]
build-std-features = ["panic_immediate_abort"]
# build-std-features = ["panic_immediate_abort", "core/turbowakers"]
